

        var stateObject = {


//------------------------------ END OF A COUNTRY , STATES AND DISTRICT-------------------------------------------------------------

"1. TPQ AN-NUR TINGGIMAE": {
                "023-74-001 ATIFAH ILHAM": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-74-002 DI'YAUL HAQ": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-74-003 ANINDITA KHAIRIN NISWA": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-74-004 ANDI NUR FILDZA": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],

            },


            //------------------------------ END OF A COUNTRY , STATES AND DISTRICT-------------------------------------------------------------



            "2. TPQ AL-MUHAJIRIN BAJENG BARAT": {
                "023-57-001 ABD. RAHMAT": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-57-002 MUH. ADRIANG HIDAYAT": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-57-003 MUH. AKBAR": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-57-004 NUR ANNISA RAMADHANI": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-57-005 SALWA SALSABILA": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-57-006 SITTI WAHYUNI RAMADANI": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],

            },



            //------------------------------ END OF A COUNTRY , STATES AND DISTRICT-------------------------------------------------------------

            "3. TPQ AL-IKHLAS PRASWIL": {
                "023-14-001 NATASYA ALFA REZKI": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-14-002 PUTRI AMELIA FEBRIANTI M": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-14-003 FAUZAN ADLI SAPUTRA": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-14-004 AINUNNISA NADIFA": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-14-005 NUR ASWHA SAFIRA": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-14-006 MUH. FATWA": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-14-007 KIEVLAN RESTU ABRISHAM": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-14-008 SITI MARYAM SUWARDY": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],

            },



            //------------------------------ END OF A COUNTRY , STATES AND DISTRICT-------------------------------------------------------------

            "4. TPQ NURUL IZZA": {
                "023-58-001 IZZAHTUL ULYA ARDAN": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-58-002 SHAFA AFDALIA MAGFIRAH": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-58-003 MUHAMMAD ALFAUSI": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-58-004 MUHAMMAD ALI AKBAR GAU": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-58-005 ARIYA WIRATAMA YATMAN": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-58-006 FARIS RIZQULLAH": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-58-007 MUH CAESAR JUNIOR": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-58-008 NURHUMAERAH": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-58-009 FELICIA HELMI": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-58-010 NUR AMELIA": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-58-011 M. ASYRAF NAUFAL": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-58-012 AZIZAH NUR FADHILLAH": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-58-013 NUR ARANA SYAMSIR": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-58-014 MUH. ANDRI PRATAMA": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-58-015 MUHAMMAD VALIANTO MAULANA": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-58-016 MUHAMMAD NURUL HIDAYAT": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-58-017 MUH. BAIHAQI KHAIZAN.S": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-58-018 ALFIAH FATHINAH ILHAM": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-58-019 KEYLA ASYIFA CAHYANI": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-58-020 HAFIZHAH HUDZAIFAH": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-58-021 SRI RAHAYU PUTRI": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-58-022 GHINA DZAKIYAH MAKNUN": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-58-023 ANDI ARDINA NURAZIFA": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-58-024 NAJID MIRZA UKAIL GADING": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-58-025 ABD. AZIZ KAHAR": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-58-026 AIRA NILAM CAHYA": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],

            },



            //------------------------------ END OF A COUNTRY , STATES AND DISTRICT-------------------------------------------------------------
            "5. TPQ BABUL FITRAH": {
                "023-119-001 NURFADILAH": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-119-002 HABIRUN HUSNA": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-119-003 MUH. IDRUS": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-119-004 AYATUN HUSNA": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-119-005 ANDIN HUSNI MARYAM": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-119-006 PISA": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],

            },



            //------------------------------ END OF A COUNTRY , STATES AND DISTRICT-------------------------------------------------------------
            "6. TPQ BAITUL HAMZAH": {
                "023-59-001 AGIL SETIAWAN": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-59-002 FAREL": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-59-003 KEYSHA KHAIRUNNISA AULIA": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-59-004 MUH RIFAL": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-59-005 MUH RISKI": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-59-006 MUH SAHRIR": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-59-007 NATASYA ARMILIA": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-59-008 NUR ASYIFA": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-59-009 RIDHO AL FITRAH": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-59-010 SRI WAHYUNI R.": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],


            },



            //------------------------------ END OF A COUNTRY , STATES AND DISTRICT-------------------------------------------------------------
            "7. TPQ NURUL IMAN TANAH BANGKA": {
                "023-110-001 NUR HIJRAH": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-110-002 NUR AQILAH": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-110-003 INDI": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-110-004 MUHAMMAD ASLAM HERMANSYAH": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-110-005 MUH ILHAM": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],

            },



            //------------------------------ END OF A COUNTRY , STATES AND DISTRICT-------------------------------------------------------------
            "8. TPQ ADZ-DZIKRO": {
                "023-60-001 AL FAIZ ASRI": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-60-002 ADIL AQSA": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-60-003 MUH FIRDAUS": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-60-004 NUR HIKMA AL SAHRA": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-60-005 KHAIRUNNISASALSABILA AKBAR": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-60-006 CAHAYA KHANA KURNIA TAJUDDIN": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],

            },



            //------------------------------ END OF A COUNTRY , STATES AND DISTRICT-------------------------------------------------------------
            "9. TPQ ASY-SYAMSI": {
                "023-61-001 MUH. ALIF AL IKHSAN KADIR": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-61-002 SITTI HAJRAH": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-61-003 MUH. NUGI TRI GUNA": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-61-004 AILA ALI": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-61-005 MOCH SYAHPUTRA AFFANDI": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-61-006 MUH. RIDWAN SAPUTRA": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-61-007 NUR ALISYA PUTRI ISNAIN": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],

            },



            //------------------------------ END OF A COUNTRY , STATES AND DISTRICT-------------------------------------------------------------
            "10. TPQ NURUL ILMI": {
                "023-62-001 ABDI": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-62-002 ALFIANSYAH. S": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-62-003 ALIF FAJAR": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-62-004 RIFKA": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-62-005 SYALSYABILA ALFARIZA": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-62-006 FAKHRA MUKARRAMAH": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-62-007 NURUL FAIZA YUSUF": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-62-008 NURFAH AINUN": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-62-009 AMELIA PUSPITA SARI ": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-62-010 HUMAERAH": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-62-011 SUCI RAMADHANI": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],

            },



            //------------------------------ END OF A COUNTRY , STATES AND DISTRICT-------------------------------------------------------------
            "11. TPQ AZZAHRA KALEGOWA": {
                "023-63-001 MUH ADRIAN SAPUTRA": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-63-002 MUHAMMAD EDY IRAWAN": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-63-003 ALIF PUTRA JUSTIN": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],

            },



            //------------------------------ END OF A COUNTRY , STATES AND DISTRICT-------------------------------------------------------------
            "12. TPQ SIPAKAINGA": {
                "023-112-001 MUH. RIDHO NASRUL": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-112-002 RESTU ALAM": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-112-003 KHAIRUL BARIYA": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-112-004 ISNANI NAURA AFIFA": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-112-005 SITI NUR AISYAH": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],

            },



            //------------------------------ END OF A COUNTRY , STATES AND DISTRICT-------------------------------------------------------------
            "13. TPQ AL-FATIH": {
                "023-69-001 CITRA CLARISTA": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-69-002 HILBRAM ALFARABY": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-69-003 SASKIA": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-69-004 NAJWA IFFA KARIMAH": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],

            },



            //------------------------------ END OF A COUNTRY , STATES AND DISTRICT-------------------------------------------------------------
            "14. TPQ KHUMAIRAH": {
                "023-72-001 ASKAL PRABAKTI": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-72-002 M. ARIS MAULANA": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-72-003 MUH. IRFAN SYAHFITRA": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-72-004 RIFKY ARFANDI": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-72-005 NUR QUROTA A'YUN": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-72-006 NUR RAISYA ALTHAFUNNISA H": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-72-007 ST. RAHMI MAHARANI": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-72-008 ZAHIRAH AYU NURFADILLAH": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],

            },



            //------------------------------ END OF A COUNTRY , STATES AND DISTRICT-------------------------------------------------------------
            "15. TPQ NURUL ISHLAH": {
                "023-75-001 AHMAD AIDAN": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-75-002 NAORA AN NUR": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-75-003 AQILAH MARITSA": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-75-004 M. LUTHFY ARDIANSYAH": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],

            },



            //------------------------------ END OF A COUNTRY , STATES AND DISTRICT-------------------------------------------------------------
            "16. TPQ DARUL FARIHIN": {
                "023-76-001 MUTHMAINNA AZIS": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-76-002 AQILA ATHIFA": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-76-003 AFIKA ZHALFA AZ-ZAHRA": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-76-004 ST ALIKHA IRFAN ANUGERAH": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-76-005 ZULFAA FATHINA ALIAH ILHAM": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-76-007 UMMU KULTSUM ALAM ADJENG": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-76-008 ANDI AWALIYAH KHANZA NABILA": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],

            },



            //------------------------------ END OF A COUNTRY , STATES AND DISTRICT-------------------------------------------------------------
            "17. TPQ AL-MUMTAZ": {
                "023-77-001 MUHAMMAD FAIZ MAULANA": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-77-002 MUH. AKMAL AHSAN": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-77-003 KAYLA RAMADANI": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-77-004 AZZAHRA AULIA PUTRI": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-77-005 AHMAD FAUZAN": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-77-007 ANDI FAUZAM AZIM": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-77-008 ANDI MUH. AMIRUL SODIQ": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],

            },



            //------------------------------ END OF A COUNTRY , STATES AND DISTRICT-------------------------------------------------------------
            "18. TPQ BAITURRAHMAN": {
                "023-78-001 ZAHRAN SYAHPUTRA KAUSI": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-78-002 MUHAMMAD DZAKIY ANSYAR": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-78-003 MUH. KULFAIZRAH. A": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-78-004 JERYCHO S.R.": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-78-005 MUH. FAJAR RAMADHAN MS.": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-78-006 MUHAMMAD AZAM ISHFAQ NUR": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-78-007 NAILAH DZAKIRAH R": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-78-008 ASYIFAH ANDI RAMADHANI": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-78-009 AZZAHRA ADNI RAMADHANI": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-78-010 RISKA APRILIANI RASJID": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-78-011 SITTI AISYAH KAMILAH SUDOMO": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-78-012 SITTI ATIFA NABILA NUR": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],

            },



            //------------------------------ END OF A COUNTRY , STATES AND DISTRICT-------------------------------------------------------------
            "19. TPQ NUR RAHMAT": {
                "023-79-001 M. HAERUL": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-79-002 RIFAL NA RUSTIA": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-79-003 RISDAYANTI": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-79-004 DEWI FEBRIYANTI": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-79-005 MUH. RIFKI MAULANA I": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-79-006 NUR SYAHYRA FAHRI": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],

            },



            //------------------------------ END OF A COUNTRY , STATES AND DISTRICT-------------------------------------------------------------
            "20. TPQ AL-MUJAHIDIN": {
                "023-80-001 ANDI MUH. KHALIL KADIR": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-80-002 ANDI ABD. KHALIQ KADIR": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],

            },



            //------------------------------ END OF A COUNTRY , STATES AND DISTRICT-------------------------------------------------------------
            "21. TPQ RAPI NUR JANNAH": {
                "023-81-001 NUR AFIKA SHAKILA ASRI": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-81-002 NADYA PUTRI ATIFA": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-81-003 ANDI CENRARA": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-81-004 MUH. RAFIF ACHMADI": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-81-005 MUHAMMAD DWI SUGIARTO": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-81-006 AKHSAN HARISYAM": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-81-007 FABIAN DWI SETYANTORO": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],

            },



            //------------------------------ END OF A COUNTRY , STATES AND DISTRICT-------------------------------------------------------------
            "22. TPQ JILUL QUR'AN": {
                "023-82-001 ALDY FIRMANSYAH": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-82-002 M. RESKY SYAWAL": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-82-003 ANDI MUHAMMAD YUSUF ZAKARIA. C": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-82-004 DEWI ANJARI KUMALA SARI": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-82-005 MUH. SHAHRUL MUBAROQ SUDIRMAN": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-82-006 NUR AFNI ILHAM": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-82-007 NUR MULIA MURSALIM": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-82-008 RAUDATUL JANNAH SUARDI": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-82-009 AZIFA KEILA ARDINI": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],

            },



            //------------------------------ END OF A COUNTRY , STATES AND DISTRICT-------------------------------------------------------------
            "23. TPQ SINAR MIFTAHUL JANNAH": {
                "023-83-001 REZA ADRIAN SYAM": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-83-002 MUH. DIRGA HIDAYAT": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-83-003 MUH. FATIR RAMADHAN": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-83-004 ANDIKA PRATAMA": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],

            },



            //------------------------------ END OF A COUNTRY , STATES AND DISTRICT-------------------------------------------------------------
            "24. TPQ FATURRAHMAN": {
                "023-84-001 AKMAL FUADY": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-84-002 MUH. RIDHO SATRIA": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-84-003 WIDYA MEGATARI": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-84-004 MUH. NAFIL ASWAN": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-84-005 MUH. DZAKY FATAHILAH AMIR": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],

            },



            //------------------------------ END OF A COUNTRY , STATES AND DISTRICT-------------------------------------------------------------
            "25. TPQ AL-IKHLAS SOMBA OPU": {
                "023-73-001 MUH. FAIZ SYARIF": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-73-002 AHYAN HABIBI NAS": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-73-003 MOHAMAD FIKRI PRATAMA ADAM": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-73-004 ANDI MUHAMMAD RIFAI RAZAK": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-73-005 ATIQAH AZAHRA SEPHANI ADAM": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],

            },



            //------------------------------ END OF A COUNTRY , STATES AND DISTRICT-------------------------------------------------------------
            "26. TPQ ASSALAM SYEH YUSUF": {
                "023-85-001 MUH. YUSUF RAZAK": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-85-002 ANDI MUH. RIDWAN": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-85-003 PARAWANSYAH": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-85-004 NUR ADNIN": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],

            },



            //------------------------------ END OF A COUNTRY , STATES AND DISTRICT-------------------------------------------------------------
            "27. TPQ AL-HIDAYAH PATTALLASSANG": {
                "023-113-001 MUHAMMAD SAUQI HASWAN": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-113-002 MUH. RAFHA HIDAYAT PRATAMA": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "011-113-003 AYUMI KIREI MICHI RAMADHANI. B": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],

            },



            //------------------------------ END OF A COUNTRY , STATES AND DISTRICT-------------------------------------------------------------
            "28. TPQ AL HAYYU": {
                "023-86-001 JUANLIFTA KARTIKA AJI": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-86-002 FANI": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],

            },



            //------------------------------ END OF A COUNTRY , STATES AND DISTRICT-------------------------------------------------------------
            "29. TPQ DAARUL JIHAD PANCANA": {
                "023-87-001 REYSA": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-87-002 AHMAD FURQAN MARDIANSA": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-87-003 LUKMANUL HAKIM": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-87-004 MUH IKHSAN PUTRA RAMADHAN": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-87-005 MUH. SYAHRUL RAMADHAN": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-87-006 AL ZAKI RAMADHAN": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-87-007 DAMIR IKRAMULLAH": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-87-008 SYIFA'U WARAHMA": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-87-009 QONITA": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-87-010 ISMA APRILIA": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-87-011 REZKY AULIA": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-87-012 SITI MARYAM AL-MUNAWWARAH": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-87-013 NUR LASTRI": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],

            },



            //------------------------------ END OF A COUNTRY , STATES AND DISTRICT-------------------------------------------------------------
            "30. TPQ BABUL FIRDAUS": {
                "023-89-001 QHAYLA SALSABILA": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-89-002 QHANITA NAJWA SYAHARA": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-89-003 SITI NURUL AZIZAH": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-89-004 SAHIRA AL ZAHRA": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-89-005 TASMIRA IMA NASIHAH": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-89-006 MULIDIA MUSTADI": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-89-007 MUH. AL HABIB": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-89-008 MARWANI KARNI": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-89-009 INDRA RAHADIAN": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-89-010 AHMAD ASLAM AL ASYAR": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-89-011 NADIA AZ ZAHRA KHAIRUL ANWAR": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],

            },



            //------------------------------ END OF A COUNTRY , STATES AND DISTRICT-------------------------------------------------------------
            "31. TPQ ARRAHMAN BUMI ZARINDA": {
                "023-88-001 HAVANA AURA KHAIRATUNHIZAN": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-88-002 AFRIANTI CHAIRUNNISA": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-88-003 MUH. AQSA PRATAMA": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-88-004 MUHAMMAD ABDULLAH RAJAB": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-88-005 RIZKI RAMADHAN": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-88-006 AISYAH APRILIAN KHUMAIRO": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],

            },



            //------------------------------ END OF A COUNTRY , STATES AND DISTRICT-------------------------------------------------------------
            "32. TPQ AMALIA": {
                "023-89-001 QHAYLA SALSABILA": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-89-002 QHANITA NAJWA SYAHARA": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-89-003 SITI NURUL AZIZAH": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-89-004 SAHIRA AL ZAHRA": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-89-005 TASMIRA IMA NASIHAH": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-89-006 MULIDIA MUSTADI": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-89-007 MUH. AL HABIB": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-89-008 MARWANI KARNI": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-89-009 INDRA RAHADIAN": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-89-010 AHMAD ASLAM AL ASYAR": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-89-011 NADIA AZ ZAHRA KHAIRUL ANWAR": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],

            },



            //------------------------------ END OF A COUNTRY , STATES AND DISTRICT-------------------------------------------------------------

            "33. TPQ BAITUL RAHMAN": {
                "023-92-001 MUH WAHYU HIDAYATULLAH S": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-92-002 MUHAMMAD ARHAM": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-92-003 NURUL AMALIA": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-92-004 NUR AINI HERMAN": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-92-005 BAGAS ANUGRAH PRATAMA MIRAD": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-92-006 AMHARA FARIS RAHMAN": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-92-007 NUR ARIQAH PUTRI": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-92-008 NUR FADILAH": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-92-009 NURUL AMALIAH  RAIS": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-92-010 NUR ASIZAH SYAM": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-92-011 MUH. NURALAMSYAH IRSAN": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-92-012 MUH. WILDAN": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-92-013 MASYTA SAHLA ARTANTI": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-92-014 ANANDA TRY SEPTIANI": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-92-015 NUR  KHALIFAH": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-92-016 ZALFA KARIMAH": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-92-017 MUH. AL AQSA": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-92-018 SYIFA MAHDIYAH": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-92-019 RINDA SRIYANTI": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-92-020 DEWI RATI": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-92-021 MUH YUSRAN AL FAUSAN ": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-92-022 ZYAQILA ANINDYA PUTRI": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-92-023 NADYA FALISHA. S": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-92-024 LUTFI AL WAHAIDI": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-92-025 MUH. SYAWAL S.": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-92-026 MUH ALGI FAHRI": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-92-027 NURUL AZIZAH INSYANI": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],

            },



            //------------------------------ END OF A COUNTRY , STATES AND DISTRICT-------------------------------------------------------------
            "34. TPQ ISTIQLAL PATTALLASSANG": {
                "023-93-001 MUH. FADLAN SYARIF": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-93-002 NURUL NAGITA ALWI": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-93-003 AKIFAH": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-93-004 NURAENI": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-93-005 MUH. FAREZA": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-93-006 ABD. RAHMAT M": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-93-007 RASYHA SYAHREZA SAPUTRA": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-93-008 NURUL APRILIANA": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-93-009 RESKI AMALIA": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-93-010 WIWI MULIANI.R": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-93-011 IBIL ERINA": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-93-012 AISYAH ARDI": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-93-013 FARID ATU RAHMAN": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-93-014 RASTI AULIA": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-93-015 MUH. YUSRIL. S": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-93-016 MUHAMMAD ZAHRAN JINAN": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-93-017 NURHIDAYAH KARIM": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-93-018 NURHALIMA": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-93-019 NURANNISAH": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],


            },



            //------------------------------ END OF A COUNTRY , STATES AND DISTRICT-------------------------------------------------------------
            "35. TPQ HIDAYATULLAH MARANNU": {
                "023-94-001 MUNARWANG MAPATAU": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-94-002 SYAHRUL RAMADHAN": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-94-003 MUH. FAIZ AL FAAT": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-94-004 NATASYA RISKI ADELIA": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-94-005 NUR REZKY PERMANA": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-94-006 AQILAH HANIFA": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-94-007 AGUNG NUR RAHMAN": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-94-008 MUH. FAEZA BAQIR AL HARIT": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-94-009 SASKIA PRADITA. Y": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-94-010 FARHAN JUBAIR": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-94-011 ASTRI": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],

            },



            //------------------------------ END OF A COUNTRY , STATES AND DISTRICT-------------------------------------------------------------
            "36. TPQ AIRIN ABIDAH": {
                "023-95-001 A. MUH. RAYYAN": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],

            },



            //------------------------------ END OF A COUNTRY , STATES AND DISTRICT-------------------------------------------------------------
            "37. TPQ ISTIQOMAH REWA": {
                "023-96-001 MUH. REHAN PRIBADI": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-96-002 MUH. NAZAR NUGRAH DARWIS": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-96-003 MUHAMMAD FADLY ADRIAN": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-96-004 ADRIAN HIDAYAT": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],

            },



            //------------------------------ END OF A COUNTRY , STATES AND DISTRICT-------------------------------------------------------------
            "38. TPQ USMANA AL AZHAR": {
                "023-97-001 ALIYAH HUMAIRA AHMAD": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-97-002 ELVIRA RANIA ZAHRA": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-97-003 WINDA SARI HAMZAH": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-97-004 TIARA": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-97-005 MUHAMMAD YUSRI PRATAMA": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],

            },



            //------------------------------ END OF A COUNTRY , STATES AND DISTRICT-------------------------------------------------------------
            "39. TPQ MASJID TUANG GURU": {
                "023-98-001 DINA ARYANTI D": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-98-002 DINI ARYANTI D": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],

            },



            //------------------------------ END OF A COUNTRY , STATES AND DISTRICT-------------------------------------------------------------
            "40. TPQ NURUL QUR'AN": {
                "023-99-001 NURUL RISQAH. K.K": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-99-002 ANDI HAERA PRABAYANTI": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-99-003 NUR ALYA SUCI RAMADANI": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-99-004 PUTRI NURFADILLAH": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-99-005 ATIIQAH PUTRI QURRATUAINI": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-99-006 MUH. IKRAM NURMAULANA LUKMAN": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],

            },



            //------------------------------ END OF A COUNTRY , STATES AND DISTRICT-------------------------------------------------------------
            "41. TPQ NUR AISHA BISSUA": {
                "023-100-001 HAIKAL": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-100-002 IRWANSYAH": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-100-003 PUTRI HANDAYANI": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],

            },



            //------------------------------ END OF A COUNTRY , STATES AND DISTRICT-------------------------------------------------------------
            "42. TPQ BAITURRAHMAN BONTOMARANNU": {
                "023-101-001 AFIFAH ALHUSNA MUSTAQIM": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-101-002 AULIYAH MADANI MUSTAQIM": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-101-003 AYATUL HUSNA": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-101-004 AUFA SATRIA SALMAN": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-101-005 ANDI NUR KEISHA AL ISHA DP": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-101-006 ANDI MUH FIKRI": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-101-007 AHMAD EZA AL GHIFARI": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-101-008 HAFIZ ALFARO SACHMAD": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-101-009 MUH. WILDAN RAJAB RIDWAN": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-101-010 MARIZKA RINDYANI": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-101-011 NURUL ATIKAH PUTRI": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-101-012 SITI AINUN FADHILAH": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],

            },



            //------------------------------ END OF A COUNTRY , STATES AND DISTRICT-------------------------------------------------------------
            "43. TPQ AN NUR PARANGBANOA": {
                "023-102-001 HARI PUTRA PRAKARSA": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-102-002 GITA NASYIFAH": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-102-003 MIFTAHUL DHAFA AL KALIFI": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-102-004 SYAWAL AL FARABY FATAQ": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],

            },



            //------------------------------ END OF A COUNTRY , STATES AND DISTRICT-------------------------------------------------------------
            "44. TPQ NUR HASANAH": {
                "023-103-001 KHUSNATUL MUTMAINNA": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-103-002 SALSA AULHIA RAMADHANI": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-103-003 AIKO SAFHIRA": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-103-004 RAKA AL PRATAMA": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-103-005 NUR AL HADID ARMAN": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-103-006 MUH ADNAN": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-103-007 M. RIFKY ALFIANSYAH A": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-103-008 MUH REIHAN NUGRAHA": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-103-009 RAFA SAPUTRA": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],

            },



            //------------------------------ END OF A COUNTRY , STATES AND DISTRICT-------------------------------------------------------------
            "45. TPQ NUR INSANI": {
                "023-104-001 ALIKA KHAERUNNISA NASUTION": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-104-002 MUHAMMAD DAVID AL FIQRA": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],

            },



            //------------------------------ END OF A COUNTRY , STATES AND DISTRICT-------------------------------------------------------------
            "46. TPQ AL-IKHLAS PANCIRO": {
                "023-105-001 NUR ASIFAH": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-105-002 SYAKINAH KARTINI": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-105-003 PUTRI AISYAH BILA": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-105-004 PUTRI ANISA": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-105-005 LUKMAINI": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-105-006 SYARFINA FEBRIANTI MAULIDA": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-105-007 RAHIM TUMENGKOL": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-105-008 RUSIADI RAHMAT": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],

            },



            //------------------------------ END OF A COUNTRY , STATES AND DISTRICT-------------------------------------------------------------
            "47. TPQ HASAN ALBANNA": {
                "023-106-001 MUH. YUSUF": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],

            },



            //------------------------------ END OF A COUNTRY , STATES AND DISTRICT-------------------------------------------------------------
            "48. TPQ AL-MUNAJAH": {
                "023-107-001 LATHIFAH FORTUNA BASRI": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-107-002 REZKI PUTRI ANGGRAINI": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-107-003 FEDYA AZILA": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-107-004 MUHAMMAD AZZAM": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-107-005 RAMEYZA ELYA": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-107-006 MUH. INRY AL-AZHAR": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],

            },



            //------------------------------ END OF A COUNTRY , STATES AND DISTRICT-------------------------------------------------------------
            "49. TPQ FHINISI JENEBERANG": {
                "023-108-001 MUH. HILAL HANDARI": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],

            },



            //------------------------------ END OF A COUNTRY , STATES AND DISTRICT-------------------------------------------------------------
            "50. TPQ MUCHLISIN": {
                "023-109-001 ZAINAL": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-109-002 ACHMAD FAUZAN A": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-109-003 RIFQI DWI  PUTRA": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-109-004 MUH. NUR RAHMAT SYAMSUDDIN": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-109-005 MUH. FAIZ HERMAWAN": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-109-006 MALIKUL ROZZAQ": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-109-007 NUR LIAH HAMJAH": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-109-008 AYU PRATIWI DARMAN": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-109-009 NAURA FAIZA KALILA": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-109-010 NAILA AZHIRA": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-109-011 SYAHRINI MANSYUR": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-109-012 SASKIA WULAN DARI": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-109-013 JIHAN SALSABILA J": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],

            },



            //------------------------------ END OF A COUNTRY , STATES AND DISTRICT-------------------------------------------------------------
            "51. TPQ AN NAAS": {
                "023-111-001 JAVIER KHAIRULLAH": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-111-002 MUHAMMAD AL FAIRUS": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-111-003 ADHARA SYAFIQAH RISMAN": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-111-004 MUH. RAFLI ALFISYAHRIN": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],

            },



            //------------------------------ END OF A COUNTRY , STATES AND DISTRICT-------------------------------------------------------------
            "52. TPQ ASSOKRA 2 PALLANGGA": {
                "023-114-001 DZAKY ATHAYA TIRTAE": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-114-002 MUHAMMAD BILAL TOPHAN": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],

            },



            //------------------------------ END OF A COUNTRY , STATES AND DISTRICT-------------------------------------------------------------
            "53. TPQ DARUL JANNAH": {
                "023-115-001 MUHAMMAD RAHMAT": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-115-002 AL JIBRIL R": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-115-003 MUHAMMAD DHAFFA PURNOMO": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],

            },



            //------------------------------ END OF A COUNTRY , STATES AND DISTRICT-------------------------------------------------------------
            "54. TPQ AL-IKHLAS TOMBOLO": {
                "023-91-001 SALMIA T": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-91-002 MUHAMMAD RANGGA SYAM": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-91-003 MUH. FACHRI": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-91-004 AMIRAH HANA FARIZA": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-91-005 SABRINA NAFIAH SUBAIR": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],

            },



            //------------------------------ END OF A COUNTRY , STATES AND DISTRICT-------------------------------------------------------------
            "55. TPQ NURUL HIKMAH BONTO CINDE": {
                "023-117-001 TITA QWENNA RIZA": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-117-002 MIFTAHUL HUSNA": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-117-003 NUR FADILAH": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-117-004 NUR FITRAH": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-117-005 SRI NIRWANA": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-117-006 FARRAS AYULIA ROEM": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-117-007 MAKAYLA PUTRI": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-117-008 KHAIDIR": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-117-009 ANDI MUHAMMAD  HILAL": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-117-010 MUHAMMAD RAYHAN": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],

            },



            //------------------------------ END OF A COUNTRY , STATES AND DISTRICT-------------------------------------------------------------
            "56. TPQ NURUL MULAIKA": {
                "023-120-001 ANAYA GHAZIAH  ISHAD": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],

            },



            //------------------------------ END OF A COUNTRY , STATES AND DISTRICT-------------------------------------------------------------
            "57. TPQ BAITUL QUR'AN AL HIKAM": {
                "023-123-001 ASHABUL KAHFI, SM": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-123-002 MUHAMMAD MUSHTAFAINAL AKHYAR SYAM": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-123-003 ADILLAH MAHARANI PUTRI": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-123-004 DAFFA ZAIDAN": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-123-005 M. ARSYAH FAIZ MAULANA N": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-123-006 MUH GIBRAN AL FARIZI": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],

            },



            //------------------------------ END OF A COUNTRY , STATES AND DISTRICT-------------------------------------------------------------
            "58. TPQ ALMUBARAK": {
                "023-124-001 TRI ANDIKA BAHAR": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-124-002 MUH. FIKRI BANGSAWAN U": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-124-003 MUH. HAEDIR ALI": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-124-004 NUR IRIANTI": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],
                "023-124-005 ANDI NABIL RAMADHAN": ["IQRA' TADARRUS", "BACAAN SHALAT", "AYAT-AYAT PILIHAN", "SURAH-SURAH PENDEK", "DO'A-DO'A HARIAN", "DINUL ISLAM", "KHAT" ],

            },



            //------------------------------ END OF A COUNTRY , STATES AND DISTRICT-------------------------------------------------------------

};
window.onload = function () {
    var countySel = document.getElementById("countySel"),
    stateSel = document.getElementById("stateSel"),
    districtSel = document.getElementById("districtSel");
    for (var country in stateObject) {
    countySel.options[countySel.options.length] = new Option(country, country);
}

countySel.onchange = function () {
    stateSel.length = 1; // remove all options bar first
    districtSel.length = 1; // remove all options bar first
    if (this.selectedIndex < 1) return; // done
    for (var state in stateObject[this.value]) {
    stateSel.options[stateSel.options.length] = new Option(state, state);
    }
}

countySel.onchange(); // reset in case page is reloaded

stateSel.onchange = function () {
    districtSel.length = 1; // remove all options bar first
    if (this.selectedIndex < 1) return; // done
    var district = stateObject[countySel.value][this.value];
    for (var i = 0; i < district.length; i++) {
        districtSel.options[districtSel.options.length] = new Option(district[i], district[i]);
        }
    }
}
